import "reset-css";
import "@fontsource-variable/fraunces/full.css";
import "@fontsource-variable/montserrat";
import "@fontsource-variable/montserrat/wght.css";
import "@fontsource-variable/montserrat/wght-italic.css";
import "./main.css";
import "./button.css";
import "./image.css";
import "./style.css";
